config/routes.rb
House::Application.routes.draw do



  namespace :api do
    resources :adverts
  end

  devise_for :users

  resources :users do
    resources :adverts
  end

  root :to => 'home#index'
  match '/' => 'home#index'
  match '/adverts' => 'home#index'
  match '/adverts/*page' => 'home#index'

  #resources :adverts

  get "contact_us/new"
  post "contact_us/send_email", :as => "send_email"

  match "/search" , :to=>"api/adverts#index"


end

app/models/account_type.rb
class AccountType < ActiveRecord::Base
  attr_accessible :name
end

app/models/advert.rb
require "babosa"
class Advert < ActiveRecord::Base

  attr_accessible :id, :category_id, :city_id, :district_id, :street_id, :house, :house_material_id,
                  :house_type_id, :rooms, :rooms_type_id, :floor, :floors, :trassa_diraction_id,
                  :purpouse_land_id, :landsize, :title, :description, :area, :life_area, :kitchen,
                  :home_deadline, :free_from, :floor_type_id, :wc_count, :state_repair_id, :ceill_height,
                  :distance, :hotadv, :price, :all_price, :usercost, :usercostforall,
                  :currency_user_id, :viewcount, :metro_station_id, :door_id,
                  :accommodation_term_id,  :preporty_location_id, :business_center_class_id,
                  :separate_entrence_id, :cabinetcount, :bussines_period_id, :layout, :image,
                  :user_id, :slug, :torg, :free_to, :operation_type_id, :commission, :flat_type_id, :video,
                  :admin, :region_id, :mapaddress, :youtube, :remote_image_url, :remote_layout_url,
                  :advert_images_attributes, :layouts_attributes, :movies_attributes, :address, :longitude, :latitude, :living

 extend FriendlyId

 friendly_id :title, use: :slugged

 def normalize_friendly_id(input)
   input.to_s.to_slug.normalize(transliterations: :russian).to_s
 end


  attr_accessor   :address

  geocoded_by :address
  after_validation :geocode

  def address
    if self.street.present? & self.city.present?
      [self.house, self.street.name, self.city.name, "UA"].compact.join(', ')

     # if self.house_changed? || self.street_id_changed? || self.city_id_changed?
      #map_download
      #end
    else
      puts self.id
    end
  end



  mount_uploader :image, ImageUploader
  mount_uploader :layout, ImageUploader
  mount_uploader :mapaddress, ImageUploader

  has_many :advert_images, :dependent => :destroy
  accepts_nested_attributes_for :advert_images, allow_destroy: true

  has_many :layouts, :dependent => :destroy
  accepts_nested_attributes_for :layouts, allow_destroy: true

  has_many :movies, :dependent => :destroy
  accepts_nested_attributes_for :movies, allow_destroy: true

  belongs_to :operation_type
  belongs_to :category
  belongs_to :region
  belongs_to :city
  belongs_to :district
  belongs_to :street
  belongs_to :accommodation_terms
  belongs_to :business_center_classes
  belongs_to :currency_users
  belongs_to :doors
  belongs_to :flat_types
  belongs_to :floor_types

  belongs_to :house_materials
  belongs_to :house_types
  belongs_to :metro_stations
  belongs_to :preporty_locations
  belongs_to :purpouse_lands
  belongs_to :rooms_types
  belongs_to :separate_entrences
  belongs_to :state_repairs
  belongs_to :trassa_diractions


  scope :search, lambda{ |b = nil| where('id = ?', "#{b}") if b.present? }

  scope :operation_type_search , lambda{|b| where(:operation_type_id => b)}
  scope :category_search, lambda{ |b| where(:category_id => b)}
  scope :living_search , lambda{|b=nil| where(b.nil? ? ''  :living => b)}
  scope :state_search, lambda{|b| where(:state => b)}
  scope :all_min_price_search, lambda{|b| where("all_price >= ?", b)}
  scope :all_max_price_search, lambda{|b| where("all_price <= ?", b)}
  scope :min_price_search, lambda{|b| where("price >= ?", b)}
  scope :max_price_search, lambda{|b| where("price <= ?", b)}
  scope :min_area_search, lambda{|b| where("area >= ?", b)}
  scope :max_area_search, lambda{|b| where("area <= ?", b)}
  scope :regoin_search, lambda{|b| where(:region_id => b)}
  scope :city_search, lambda{|b| where(:city_id => b)}

  scope :search_by_type,lambda{|b| where(:category_id => b)}

  def self.all_cached
    Rails.cache.fetch('Contact.all') { all }
  end

  def map_download
    require 'open-uri'
    map = "#{uuid}.png"
    @path = "#{store_dir}/#{map}"
    open(@path, 'wb') do |file|
      file << open(static_map).read
    end
    self.mapaddress = "test.png"
    self.save
  end

  def uuid
    UUID.state_file = false
    uuid = UUID.new
    uuid.generate

  end

  def static_map
    params = {
        :center => [self.latitude, self.longitude].join(","),
        :zoom => 12,
        :size => "300x300",
        :markers => [self.latitude, self.longitude].join(","),
        :sensor => false
    }
    query_string =  params.map{|k,v| "#{k}=#{v}"}.join("&")
    @c = "http://maps.googleapis.com/maps/api/staticmap?#{query_string}"
    @c
  end

  def store_dir
    "uploads/#{self.class.to_s.underscore}/map/#{self.id}"
  end

end

app/models/advert_image.rb
class AdvertImage < ActiveRecord::Base
  attr_accessible :advert_id, :image, :remote_image_url
  mount_uploader :image, ImageUploader
  belongs_to :advert
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
  alias_attribute :title, :name
  has_many :adverts
end

app/models/city.rb
class City < ActiveRecord::Base
  attr_accessible :region_id, :name
  alias_attribute :title, :name
  has_many :adverts
  has_many :streets
  has_many :districts
  belongs_to :region
end

app/models/contact_form.rb
class  ContactForm
  include ActiveModel::Validations
  include ActiveModel::Conversion

  attr_accessor :name, :email, :body
  validates_presence_of :name, :email, :body


  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end


end

app/models/currency_user.rb
class CurrencyUser < ActiveRecord::Base
  attr_accessible :name
  alias_attribute :title, :name
  has_many :adverts
end

app/models/district.rb
class District < ActiveRecord::Base
  attr_accessible :city_id, :name
  alias_attribute :title, :name
  has_many :adverts
  belongs_to :city
end

app/models/door.rb
class Door < ActiveRecord::Base
  attr_accessible :name
  alias_attribute :title, :name
  has_many :adverts
end

app/models/flat_type.rb
class FlatType < ActiveRecord::Base
  attr_accessible :name
  alias_attribute :title, :name
  has_many :adverts
end

app/models/floor_type.rb
class FloorType < ActiveRecord::Base
  attr_accessible :name
  alias_attribute :title, :name
  has_many :adverts
end

app/models/house_type.rb
class HouseType < ActiveRecord::Base
  attr_accessible :name, :category_id
  alias_attribute :title, :name
  has_many :adverts
end

app/models/info_contact.rb
class InfoContact < ActiveRecord::Base
  attr_accessible :account_type_id, :comissionvalue, :commission_id, :email, :fio, :logocompany, :skype, :tel, :tel2
end

app/models/layout.rb
class Layout < ActiveRecord::Base
  attr_accessible :advert_id, :image, :remote_image_url
  mount_uploader :image, ImageUploader
  belongs_to :advert
end

app/models/metro_station.rb
class MetroStation < ActiveRecord::Base
  attr_accessible :city_id, :name
  alias_attribute :title, :name
  has_many :adverts
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  attr_accessible :advert_id, :video
  belongs_to :advert
end

app/models/region.rb
class Region < ActiveRecord::Base
  attr_accessible :name
  alias_attribute :title, :name
  has_many :adverts
  has_many :cities
end

app/models/rooms_type.rb
class RoomsType < ActiveRecord::Base
  attr_accessible :name
  alias_attribute :title, :name
  has_many :adverts
end

app/models/state_repair.rb
class StateRepair < ActiveRecord::Base
  attr_accessible :name
  alias_attribute :title, :name
  has_many :adverts
end

app/models/street.rb
class Street < ActiveRecord::Base
  attr_accessible :city_id, :name, :district_id
  alias_attribute :title, :name
  has_many :adverts
  belongs_to :city
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/views/layouts/_cache_stat.html.haml
-if @stats
  = render "adverts/cache"

app/views/layouts/_footer.html.haml
/ Footer
%footer.row
  .large-12.columns
    %hr/
    .row
      .large-6.columns
        %p &copy; Copyright .
      .large-6.columns

/ End Footer

app/views/layouts/_sidebar.html.haml
/ Sidebar
.row
  .large-12.columns
    = render "adverts/search"
    = render "adverts/search_by_id"
    = render "adverts/sidebar_adverts_count"

/ End Sidebar

app/views/layouts/_sidebar_medium.html.haml
= render "adverts/search_medium"
= render "adverts/search_by_id"
= render "adverts/sidebar_adverts_count"

/ End Sidebar

app/views/layouts/_top_bar.html.haml
%nav#top_bar.breadcrumbs{:style => "margin-bottom: 20px;"}
  = link_to 'Недвижимость', adverts_path

  - if user_signed_in?
    = link_to('new', new_user_advert_path(current_user))

  %a.back_link{:href => "javascript:history.back()", :title => ""}
    %span назад
  = Time.now.strftime("%y.%m.%d %H:%M ")

app/views/layouts/application.html.haml
!!!
/ paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/
/[if lt IE 7 ] <html class=\"ie6\" lang=\"en\">
/[if IE 7 ]    <html class=\"ie7\" lang=\"en\">
/[if IE 8 ]    <html class=\"ie8\" lang=\"en\">
/[if IE 9 ]    <html class=\"ie9\" lang=\"en\">
/[if (gt IE 9)|!(IE)] <!--> <html lang=\"en\">
%html(ng-app="realty")
  / <![endif]
  %head
    %meta{:charset => "utf-8"}/
    / Uncomment to make IE8 render like IE7
    / <meta http-equiv="X-UA-Compatible" content="IE=7" />
    / Set the viewport width to device width for mobile
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "Untitled"
    = stylesheet_link_tag    "application", :media => 'all'
    = javascript_include_tag "vendor/custom.modernizr"
    = csrf_meta_tags
    %base{:href=>"/"}
  %body#page.off-canvas.hide-extras
    .container
      = render 'layouts/top_bar'
      / Main Page Content and Sidebar
      %p.small-block
        %a#sidebarButton.sidebar-button.dorohouse_button{:href => "#sidebar"} Search
      .row
        %section#sidebar{:role => "complementary"}
          %nav#sideMenu{:role => "navigation"}
            #sideMainNav.nav-bar
              = render 'layouts/sidebar'
        .large-3.columns.hide-for-small.hide-for-medium= render 'layouts/sidebar'
        .large-3.columns.show-for-medium= render 'layouts/sidebar_medium'
        .large-9.columns
          = yield
      / End Main Content and Sidebar
      = render 'layouts/footer'
    = javascript_include_tag "http://maps.googleapis.com/maps/api/js?sensor=false&language=ru"
    = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/gsap/1.9.7/TweenMax.min.js"
    = javascript_include_tag "application"